name: Main

on:
  # 允许你从 Actions 页面手动触发此工作流
  workflow_dispatch:

  # 当有代码推送到 master-mod-package 分支时触发
  push:
    branches: [ master-mod-package ]

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create Debug Keystore
        run: |
          mkdir -p ~/.config/.android
          keytool -genkey -v -keystore ~/.config/.android/debug.keystore \
            -alias androiddebugkey -storepass android -keypass android \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Android Debug,O=Android,C=US"
            
      - name: Configure build properties
        run: echo "buildWithGitSuffix=true" > local.properties

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Debug APK
        id: buildDebug
        run: |
          ./gradlew :app:assembleDebug
          echo "debugName=$(basename app/build/outputs/apk/debug/app-debug.apk .apk)" >> $GITHUB_OUTPUT

      - name: Upload Debug APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.buildDebug.outputs.debugName }}
          path: app/build/outputs/apk/debug/app-debug.apk
